### ISSUE TITLE
Method not found: EnvDTE.Solution

### ISSUE THREAD

**Issue by matnatx** [jeffdapaz/VisualChatGPTStudio#69]
I got the latest version of the source code and started debugging the extension with VS 2022. When I use any of the Visual chatGPT Studio commands (e.g Explain) I get the following error popup:

**Visual chatGPT Studio**

```
Method not found: 'EnvDTE.Solution
EnvDTE._DTE.get_Solution()
```

The exception stack trace is:

```csharp

   at JeffPires.VisualChatGPTStudio.Options.Commands.OptionCommands.<GetCommandAsync>d__8.MoveNext() in D:\Projects\VisualChatGPTStudio-master\VisualChatGPTStudioShared\Options\Commands\OptionCommands.cs:line 139
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at JeffPires.VisualChatGPTStudio.Options.Commands.OptionCommands.GetCommandAsync(CommandsType commandType) in D:\Projects\VisualChatGPTStudio-master\VisualChatGPTStudioShared\Options\Commands\OptionCommands.cs:line 98
   at JeffPires.VisualChatGPTStudio.Explain.GetCommand(String selectedText) in D:\Projects\VisualChatGPTStudio-master\VisualChatGPTStudioShared\Commands\Explain.cs:line 17
   at JeffPires.VisualChatGPTStudio.Commands.BaseGenericCommand`1.<RequestAsync>d__10.MoveNext() in D:\Projects\VisualChatGPTStudio-master\VisualChatGPTStudioShared\Commands\BaseGenericCommand.cs:line 98
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at JeffPires.VisualChatGPTStudio.Commands.BaseGenericCommand`1.<ExecuteAsync>d__9.MoveNext() in D:\Projects\VisualChatGPTStudio-master\VisualChatGPTStudioShared\Commands\BaseGenericCommand.cs:line 77

```

**Comment by jeffdapaz** [comment]
Hi @matnatx ,

I don't know what it could be, but at the moment it could be a different version of a specific library.

Compare it with what I have on my side and try to leave it in the same versions if any of them are different:

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/1cf783f3-7718-4656-addc-eb12324eb3e6)

![image](https://github.com/jeffdapaz/VisualChatGPTStudio/assets/63928228/c2156f38-12f9-4061-893d-390fa32614aa)

Just to confirm, any chance of your VS 2022 being the ARM edition?

**Comment by jeffdapaz** [comment]
@matnatx,

Maybe you were able to solve the problem, but if not, you can come back here and let me know.
