### ISSUE TITLE
Parameter count mismatch while getting code suggestions

### ISSUE THREAD

**Issue by marriajoseph** [jeffdapaz/VisualChatGPTStudio#80]
Hello,
I'm having a crash with code suggestions with a custom model using ollama.
The log shows that the request is sent and the response seems to be correct, but something is not valid for the plugin.

9/10/2024 4:23:39 AM: Request URI: http://127.0.0.1:11434/v1/chat/completions
9/10/2024 4:23:39 AM: Request Method: POST
9/10/2024 4:23:39 AM: Request Headers:
9/10/2024 4:23:39 AM: Accept-Encoding: gzip, deflate
9/10/2024 4:23:39 AM: Connection: keep-alive
9/10/2024 4:23:39 AM: Authorization: Bearer ollama
9/10/2024 4:23:39 AM: api-key: ollama
9/10/2024 4:23:39 AM: User-Agent: okgodoit/dotnet_openai_api
9/10/2024 4:23:39 AM: Request Content: {"model":"codellama:latest","messages":[{"role":"system","content":"Please complete.. Please, only provide the code without additional comments or text. , and do not repeat the same code that I send in your response."},{"role":"user","content":"int get_next_prime(int a)\r\n\r\n"}],"temperature":0.0,"top_p":0.0,"n":1,"stream":false,"max_tokens":4096,"frequency_penalty":0.5,"presence_penalty":0.0}
9/10/2024 4:23:39 AM: ____________________________________________________________________________________________________
9/10/2024 4:23:40 AM: Response Headers:
9/10/2024 4:23:40 AM: Date: Tue, 10 Sep 2024 11:23:40 GMT
9/10/2024 4:23:40 AM: Response Status Code: OK
9/10/2024 4:23:40 AM: Response Content: {"id":"chatcmpl-124","object":"chat.completion","created":1725967420,"model":"codellama:latest","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":"```scss\r\nint get_next_prime(int a) {\r\n  while (!isPrime(a)) {\r\n    a++;\r\n  }\r\n  return a;\r\n}\r\n```"},"finish_reason":"stop"}],"usage":{"prompt_tokens":62,"completion_tokens":45,"total_tokens":107}}

9/10/2024 4:23:40 AM: ____________________________________________________________________________________________________
9/10/2024 4:23:40 AM: System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at JeffPires.VisualChatGPTStudio.Copilot.Suggestions.<ShowAutocompleteAsync>d__8.MoveNext() in C:\Source\GIT\VisualChatGPTStudio\Copilot\Suggestions.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JeffPires.VisualChatGPTStudio.Copilot.InlinePredictionManager.<OnEnterPressed>d__5.MoveNext() in C:\Source\GIT\VisualChatGPTStudio\Copilot\InlinePredictionManager.cs:line 89

**Comment by jeffdapaz** [comment]
Hi @marriajoseph,

the problem is not related with ollama, I was able to simulate the same error using Azure OpenAI.

When I have time, I will look further and provide a fix.

**Comment by jeffdapaz** [comment]
@marriajoseph,

I published a new version with the fix.

If anything you can reopen this issue.

**Comment by jeffdapaz** [comment]
Hi @Asafima ,

for what I remember, the issue was related with the Visual Studio version.

What is the version of the VS you are using now? This issue started happening after you updated the VS?

**Comment by jeffdapaz** [comment]
Ok, I figured out how to make this work again.

I already published the new version.
